languageCode = "en-us"
title = "tutorial"
theme = ["reveal-hugo"]

[markup.goldmark.renderer]
unsafe = true

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true

[params.reveal_hugo]
hash = true
slide_number = true
width = 1920
height = 1080
chalkboard = { theme = "whiteboard" }
customcontrols = { controls = [ { icon = "<i class=\"fa fa-pen-square\"></i>", title = "Toggle chalkboard(B)", action = "RevealChalkboard.toggleChalkboard();" }, { icon = "<i class=\"fa fa-pen\"></i>", title = "Toggle notes canvas (C)", action = "RevealChalkboard.toggleNotesCanvas();" } ] }
mathjax_cdn = "/module/Mathjax/script.js"
mermaid_cdn = "/module/Mermaid/script.js"

[markup.highlight]
codeFences = false

[markup.goldmark.parser.attribute]
title = true
block = true

[[params.reveal_hugo.plugins]]
name = "RevealChalkboard"
source = "module/RevealPlugins/Chalkboard/script.js"
css = "module/RevealPlugins/Chalkboard/style.css"

[[params.reveal_hugo.plugins]]
name = "RevealCustomControls"
source = "module/RevealPlugins/CustomControl/script.js"
css = "module/RevealPlugins/CustomControl/style.css"

[[params.reveal_hugo.plugins]]
name = "Externalcode"
source = "module/RevealPlugins/RevealExternalCode/script.js"

[[params.reveal_hugo.plugins]]
name = "RevealHighlight"
source = "reveal-js/plugin/highlight/highlight.js"
